# Generated by Django 3.2.16 on 2022-10-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('dairy', 'dairy'), ('beverages', 'beverages'), ('frozen vegetables', 'frozen vegetables'), ('meat', 'meat'), ('fruits', 'fruits')], max_length=100)),
                ('food_title', models.CharField(max_length=120)),
                ('photos', models.ImageField(upload_to='uploaded_images/')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app1.profile')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
