# Generated by Django 3.2.16 on 2022-10-14 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='avatar.png', upload_to='profile_pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('dairy', 'dairy'), ('beverages', 'beverages'), ('frozen vegetables', 'frozen vegetables'), ('meat', 'meat'), ('fruits', 'fruits')], max_length=100)),
                ('food_title', models.CharField(max_length=120)),
                ('photos', models.ImageField(upload_to='uploaded_images/')),
                ('price', models.FloatField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profile')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
