# Generated by Django 3.2.16 on 2022-10-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_image'),
        ('app1', '0006_alter_item_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
